// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Bnidy79SSyBfPOxXQCWpzTovKGdHSRU',
    appId: '1:1078359871583:web:76f3460661835096a64bea',
    messagingSenderId: '1078359871583',
    projectId: 'xyz1-6de24',
    authDomain: 'xyz1-6de24.firebaseapp.com',
    storageBucket: 'xyz1-6de24.appspot.com',
    measurementId: 'G-S2S6X77XQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rBGYS02fPVSsQFYLzTJhFq7s5HVDNGE',
    appId: '1:1078359871583:android:147e76a098a3b359a64bea',
    messagingSenderId: '1078359871583',
    projectId: 'xyz1-6de24',
    storageBucket: 'xyz1-6de24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOuzShgrwlG51M12Mp3Qy3LmrjZe4yzfQ',
    appId: '1:1078359871583:ios:6e928e93dbeea844a64bea',
    messagingSenderId: '1078359871583',
    projectId: 'xyz1-6de24',
    storageBucket: 'xyz1-6de24.appspot.com',
    iosBundleId: 'com.example.worknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOuzShgrwlG51M12Mp3Qy3LmrjZe4yzfQ',
    appId: '1:1078359871583:ios:6e928e93dbeea844a64bea',
    messagingSenderId: '1078359871583',
    projectId: 'xyz1-6de24',
    storageBucket: 'xyz1-6de24.appspot.com',
    iosBundleId: 'com.example.worknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Bnidy79SSyBfPOxXQCWpzTovKGdHSRU',
    appId: '1:1078359871583:web:76f3460661835096a64bea',
    messagingSenderId: '1078359871583',
    projectId: 'xyz1-6de24',
    authDomain: 'xyz1-6de24.firebaseapp.com',
    storageBucket: 'xyz1-6de24.appspot.com',
    measurementId: 'G-1ZBYLGJJMG',
  );
}
